### ISSUE TITLE
Suddenly missing from the Terraform Registry

### ISSUE THREAD

**Issue by disambiguationuk** [inuits/terraform-provider-cortex#20]
Just this last week when trying to pull version 0.0.3 from the Terraform Registry:

```
│ Could not retrieve the list of available versions for provider inuits/cortex: no available releases match the given constraints 0.0.3
```

**Comment by landervdb** [comment]
Hi @disambiguationuk, this seems to be working on my end, could you confirm it's still broken for you?

**Comment by disambiguationuk** [comment]
Yeah I still get this after clearing my terraform cache. Maybe you've still got a cached version @landervdb? 

We've forked and published vivacitylabs/cortex to get around this for now.

![image](https://github.com/inuits/terraform-provider-cortex/assets/11738048/e97e7a8b-a2e2-4d3d-a98c-c85f36cdb90a)

**Comment by KrisBuytaert** [comment]
@disambiguationuk   I just tried from a fresh checkout ,  

`git clone https://github.com/inuits/terraform-provider-cortex/
Cloning into 'terraform-provider-cortex'...
remote: Enumerating objects: 214, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 214 (delta 58), reused 48 (delta 48), pack-reused 138
Receiving objects: 100% (214/214), 150.39 KiB | 2.31 MiB/s, done.
Resolving deltas: 100% (96/96), done.
sdog@fedora:/home/o11y$ cd terraform-provider-cortex/examples/
sdog@fedora:/home/o11y/terraform-provider-cortex/examples$ tofu init 

Initializing the backend...

Initializing provider plugins...
- Finding inuits/cortex versions matching "0.0.3"...
- Installing inuits/cortex v0.0.3...
- Installed inuits/cortex v0.0.3. Signature validation was skipped due to the registry not containing GPG keys for this provider

OpenTofu has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that OpenTofu can guarantee to make the same selections by default when
you run "tofu init" in the future.

OpenTofu has been successfully initialized!

You may now begin working with OpenTofu. Try running "tofu plan" to see
any changes that are required for your infrastructure. All OpenTofu commands
should now work.

If you ever set or change modules or backend configuration for OpenTofu,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
`

As  you can see .. it worked out of the box

**Comment by disambiguationuk** [comment]
Is that initializing from your locally cloned repo or from the terraform registry?

**Comment by KrisBuytaert** [comment]
It's absolutely coming from the internet ..  but  from the opentofu registry

**Comment by landervdb** [comment]
works for me with actual terraform as well as opentofu:
```
➜ cd $(mktemp -d)

/tmp/tmp.Bdnso0DnrU …
➜ git clone https://github.com/inuits/terraform-provider-cortex/
Cloning into 'terraform-provider-cortex'...
remote: Enumerating objects: 214, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 214 (delta 58), reused 48 (delta 48), pack-reused 138
Receiving objects: 100% (214/214), 150.39 KiB | 2.28 MiB/s, done.
Resolving deltas: 100% (96/96), done.

/tmp/tmp.Bdnso0DnrU …
➜ cd terraform-provider-cortex/examples/

terraform-provider-cortex/examples on 🐳 v26.0.0 …
➜ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding inuits/cortex versions matching "0.0.3"...
- Installing inuits/cortex v0.0.3...
- Installed inuits/cortex v0.0.3 (self-signed, key ID C52C0579BDA9D8D3)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by landervdb** [comment]
The [TF registry](https://registry.terraform.io/providers/inuits/cortex/latest) also still knows about it and indicates 81 downloads this week...

**Comment by disambiguationuk** [comment]
Hmm you're right, its started working again. It deffo wasn't before though. Had issues across multiple machines with multiple users over the space of a few weeks, although it was more likely a TF registry issue. Regardless we've got darwin users who can't use the package so we're still using our fork. Cheers.
